### ISSUE TITLE
Don't support loading more ??

### ISSUE THREAD

**Issue by yanxinmiao** [Yalantis/pull-to-make-soup#2]

**Comment by TeeRawk** [comment]
Hi,can you please provide more details ?

**Comment by yuanzhuohao** [comment]
Example, The RecyclerView don't pull up.

**Comment by yuanzhuohao** [comment]
Can I custom any animated pull to refresh added to RecyclerView???

**Comment by TeeRawk** [comment]
Do you mean it's not working with RecyclerView ?
No it's not avalible right now to customze the animation.

**Comment by TeeRawk** [comment]
Closed, not enough information
