### ISSUE TITLE
Flames/Water views leave is delayed

### ISSUE THREAD

**Issue by bradmartin** [Yalantis/pull-to-make-soup#3]
The water and flames views don't animate out after setting the refreshing to false. The other views look fine. Any suggestions on specifics for the layout or possible causes? Tested both on Android 6.0 and 5.1

![soup](https://cloud.githubusercontent.com/assets/6006148/15347575/73b29f80-1c88-11e6-9ac0-021f76faba89.gif)

**Comment by TeeRawk** [comment]
Hello ,again.  I'm working on a way to fix this. Thanks for th gif image,that's help alot in understanding .

**Comment by bradmartin** [comment]
Great, hope to see a good fix soon :smile: thanks for checking it out.

**Comment by bradmartin** [comment]
Once I set the listview items to have a background, I don't see this behavior anymore. Since it gets covered up, so that's a workaround for now 👍

**Comment by TeeRawk** [comment]
Hello,  there's a new version avalible that fixes this issue .:)

**Comment by bradmartin** [comment]
Awesome. Thanks I'll try it out later.

**Comment by bradmartin** [comment]
Thanks for the fix!
