### ISSUE TITLE
Question: SoupView shown when swiping up

### ISSUE THREAD

**Issue by bradmartin** [Yalantis/pull-to-make-soup#4]
In the attached .gif you'll see the soup refresh works fine when pulling down (swipe down) but when swiping up at the top of the list, the soup pops in (as seen in gif). Is this intended?

![touchsoup](https://cloud.githubusercontent.com/assets/6006148/15347603/c91bb5ce-1c88-11e6-917e-3ef2117e1c81.gif)

**Comment by TeeRawk** [comment]
Hello, bradmartin, thanks for informative response. I've searched a bit , and found out it's a common behaviour of pull to refresh. However if u want to avoid it make ur list items not transperent, but white( if we're talking about this example).

**Comment by bradmartin** [comment]
Thanks for the info.
